import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ChevronDown, Gauge, Fuel, ShieldCheck, SlidersHorizontal } from "@/lib/lucide-react";
import { MagazineFooter } from "@/components/MagazineFooter";
import { MagazineHeader } from "@/components/MagazineHeader";

const vehicles = [
  { id: "tenere", name: "Yamaha Ténéré 700", type: "DUAL-SPORT ADVENTURE", engine: "689cc CP2 Parallel-Twin (72.4 hp)", weight: "205 kg (wet)", price: "$10,799 USD", rating: "8.7 / 10", economy: "23.8 km/L" },
  { id: "cfmoto", name: "CFMoto 450 MT", type: "LIGHTWEIGHT MID-ADVENTURE", engine: "449cc 270° Parallel-Twin (44 hp)", weight: "190 kg (wet)", price: "$6,499 USD", rating: "9.2 / 10", economy: "26.5 km/L" },
  { id: "miata", name: "Mazda MX-5 Miata ND3", type: "LIGHTWEIGHT SPORTS ROADSTER", engine: "2.0L Skyactiv-G 4-Cyl (181 hp)", weight: "1,061 kg", price: "$28,985 USD", rating: "8.1 / 10", economy: "14.5 km/L" },
];

function ToolsHeading({ eyebrow, title, description, id }: { eyebrow: string; title: string; description: string; id: string }) {
  return <div className="section-heading" data-testid={`${id}-heading-group`}><div className="section-heading-copy"><span className="eyebrow" data-testid={`${id}-eyebrow`}>{eyebrow}</span><h2 data-testid={`${id}-title`}>{title}</h2></div><p data-testid={`${id}-description`}>{description}</p></div>;
}

export default function Tools() {
  const [trackMode, setTrackMode] = useState(true);
  const [vehicleA, setVehicleA] = useState("tenere");
  const [vehicleB, setVehicleB] = useState("cfmoto");
  const [showCompare, setShowCompare] = useState(false);
  const [dailyKm, setDailyKm] = useState("45");
  const [efficiency, setEfficiency] = useState("14.5");
  const [tax, setTax] = useState("320");
  const [livery, setLivery] = useState("#FF6600");
  const [mask, setMask] = useState(false);
  const selectedVehicles = [vehicles.find((vehicle) => vehicle.id === vehicleA) ?? vehicles[0], vehicles.find((vehicle) => vehicle.id === vehicleB) ?? vehicles[1]];
  const monthlyCost = useMemo(() => ((Number(dailyKm) || 0) * 30.5 / (Number(efficiency) || 1)) * 1.75 + (Number(tax) || 0) / 12, [dailyKm, efficiency, tax]);

  return (
    <div className={`daily-driver-app tools-page ${trackMode ? "track-mode" : "street-mode"}`} data-testid="tools-page">
      <MagazineHeader trackMode={trackMode} onToggleMode={() => setTrackMode((mode) => !mode)} />
      <main className="tools-main" data-testid="tools-main"><div className="tools-intro"><span className="eyebrow" data-testid="tools-eyebrow">DAILY DRIVER // INSTRUMENTS</span><h1 data-testid="tools-title">THE TOOLS<br /><em>BEHIND THE DRIVE.</em></h1><p data-testid="tools-description">Compare the fleet, price the commute, and spec a machine that feels like yours. These are the practical instruments behind the magazine.</p></div>
        <section className="interactive-section tools-section" id="garage" data-testid="tools-garage-section"><ToolsHeading id="tools-garage" eyebrow="01 // THE GARAGE" title="SPEC SHEET COMPARISON" description="Select two machines from the fleet to compare daily livability, engine character, and real-world commuter ratings." /><div className="garage-layout"><div className="garage-controls" data-testid="tools-garage-controls"><div className="control-field"><label htmlFor="tools-vehicle-a" data-testid="tools-vehicle-a-label">VEHICLE A</label><div className="select-wrap"><select id="tools-vehicle-a" value={vehicleA} onChange={(event) => setVehicleA(event.target.value)} data-testid="tools-vehicle-a-select">{vehicles.map((vehicle) => <option value={vehicle.id} key={vehicle.id}>{vehicle.name}</option>)}</select><ChevronDown size={16} /></div></div><div className="control-field"><label htmlFor="tools-vehicle-b" data-testid="tools-vehicle-b-label">VEHICLE B</label><div className="select-wrap"><select id="tools-vehicle-b" value={vehicleB} onChange={(event) => setVehicleB(event.target.value)} data-testid="tools-vehicle-b-select">{vehicles.map((vehicle) => <option value={vehicle.id} key={vehicle.id}>{vehicle.name}</option>)}</select><ChevronDown size={16} /></div></div><Button className="outline-button" onClick={() => setShowCompare((show) => !show)} data-testid="tools-compare-button">{showCompare ? "HIDE COMPARISON" : "COMPARE MACHINES"}<SlidersHorizontal size={16} /></Button><div className="garage-note" data-testid="tools-garage-note"><ShieldCheck size={16} /><span>Specs verified by the Daily Driver test bench.</span></div></div>{showCompare && <div className="comparison-sheet" data-testid="tools-comparison-sheet"><div className="comparison-head"><span className="eyebrow" data-testid="tools-comparison-label">LIVE COMPARISON</span></div><div className="vehicle-columns">{selectedVehicles.map((vehicle, index) => <div className="vehicle-column" key={vehicle.id} data-testid={`tools-vehicle-${index === 0 ? "a" : "b"}-column`}><div className="vehicle-column-title"><span data-testid={`tools-vehicle-${index === 0 ? "a" : "b"}-type`}>{vehicle.type}</span><h3 data-testid={`tools-vehicle-${index === 0 ? "a" : "b"}-name`}>{vehicle.name}</h3></div>{[["ENGINE", vehicle.engine], ["WEIGHT", vehicle.weight], ["PRICE", vehicle.price], ["COMMUTE RATING", vehicle.rating]].map(([label, value]) => <div className="spec-cell" key={label} data-testid={`tools-vehicle-${index === 0 ? "a" : "b"}-${label.toLowerCase().replaceAll(" ", "-")}`}><span className="spec-label">{label}</span><strong>{value}</strong></div>)}<div className="mini-spec-row"><span>ECONOMY</span><strong>{vehicle.economy}</strong></div></div>)}</div></div>}</div></section>
        <section className="interactive-section tools-section" id="ownership" data-testid="tools-ownership-section"><ToolsHeading id="tools-ownership" eyebrow="02 // RUNNING METRICS" title="COST OF OWNERSHIP" description="Calculate the true monthly cost of the route you actually drive, using the $1.75/L benchmark." /><div className="ownership-panel"><div className="ownership-fields" data-testid="tools-calculator-form"><div className="control-field"><label htmlFor="tools-daily-km" data-testid="tools-daily-km-label">DAILY COMMUTE <span>(KM)</span></label><Input id="tools-daily-km" type="number" value={dailyKm} onChange={(event) => setDailyKm(event.target.value)} data-testid="tools-daily-km-input" /></div><div className="control-field"><label htmlFor="tools-efficiency" data-testid="tools-efficiency-label">FUEL EFFICIENCY <span>(KM/L)</span></label><Input id="tools-efficiency" type="number" value={efficiency} onChange={(event) => setEfficiency(event.target.value)} data-testid="tools-efficiency-input" /></div><div className="control-field"><label htmlFor="tools-tax" data-testid="tools-tax-label">ANNUAL TAX</label><Input id="tools-tax" type="number" value={tax} onChange={(event) => setTax(event.target.value)} data-testid="tools-tax-input" /></div><p className="fuel-note" data-testid="tools-fuel-note"><Fuel size={15} /> Benchmark fuel price: <strong>$1.75 / L</strong></p></div><div className="cost-output" data-testid="tools-monthly-cost"><span>MONTHLY RUNNING COST</span><strong data-testid="tools-monthly-cost-value">${monthlyCost.toFixed(2)}</strong><small>EST. USD // 30.5 DAYS</small></div></div></section>
        <section className="interactive-section tools-section" id="livery" data-testid="tools-livery-section"><ToolsHeading id="tools-livery" eyebrow="03 // PAINT BOOTH" title="LIVERY VISUALIZER" description="Switch color swatches and test windshield masking in a race-paddock paint booth." /><div className="livery-layout"><div className="livery-preview" data-testid="tools-livery-preview"><div className="preview-grid" /><span className="preview-label">DAILY DRIVER // TEST CAR 01</span><div className="vehicle-silhouette" style={{ backgroundColor: livery }} data-testid="tools-vehicle-silhouette"><div className={`vehicle-windshield ${mask ? "masked" : ""}`} data-testid="tools-vehicle-windshield">{mask && <span>MASKED</span>}</div><div className="vehicle-roof" /><div className="vehicle-cabin" /><div className="vehicle-wheel wheel-one" /><div className="vehicle-wheel wheel-two" /></div><span className="preview-caption">LIVERY / {livery}</span></div><div className="livery-controls" data-testid="tools-livery-controls"><div><span className="control-title">SELECT LIVERY COLOR</span><div className="swatch-row">{[["#1A1A1A", "ASPHALT BLACK"], ["#FF6600", "ORANGE SAFETY"], ["#CCCCCC", "STEEL SILVER"]].map(([color, label]) => <button className={`color-swatch ${livery === color ? "selected" : ""}`} style={{ backgroundColor: color }} onClick={() => setLivery(color)} aria-label={`Select ${label}`} key={color} data-testid={`tools-swatch-${label.toLowerCase().replaceAll(" ", "-")}`}><span>{livery === color ? "✓" : ""}</span></button>)}</div><div className="swatch-names"><span data-testid="tools-current-livery">{livery === "#FF6600" ? "ORANGE SAFETY" : livery === "#CCCCCC" ? "STEEL SILVER" : "ASPHALT BLACK"}</span><span>RAL // AUTOMOTIVE</span></div></div><div className="mask-control"><div><span className="control-title">APPLY WINDSHIELD MASKING</span><small>Leave the glass blank for a clean race-day silhouette.</small></div><button className={`binary-toggle ${mask ? "active" : ""}`} onClick={() => setMask((value) => !value)} aria-pressed={mask} data-testid="tools-windshield-toggle"><span /></button></div><div className="livery-specs"><span><Gauge size={16} /><strong>AERO PACKAGE / 02</strong></span><span><SlidersHorizontal size={16} /><strong>CONFIGURATOR READY</strong></span></div></div></div></section>
      </main>
      <MagazineFooter />
    </div>
  );
}